Labels_Nudges/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.conf.urls import handler404, handler500

app_name = "Labels_Nudges"

urlpatterns = [
    path('',views.home, name='home'),
    path('personal_info', views.personal_info, name='personal_info'),
    path('ghs_fk', views.ghs_fk, name = 'ghs_fk'), 
    path('selectRecipe',views.selectRecipe,name='selectRecipe'),
    # path('rate_items', views.rate_items, name='rate_items'),
    path('boost', views.nutrition_labels, name='nutrition_labels'),
    path('recipe_recommendations', views.recipe_recommendations, name = 'recipe_recommendations' ),
    path('choice_evaluation',views.choice_evaluation, name='choice_evaluation'),
    path('thank_u',views.thank_u, name='thank_u'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.error_404
handler500 = views.error_500

NudgingWithFoodLabels/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Labels_Nudges.urls')),
]

Labels_Nudges/views.py
from select import select
from django.forms import formset_factory
from django.db.models import Count
import datetime
# from datetime import datetime
import pandas as pd
from random import choice, sample
import random
from sys import prefix
from django import forms
from django.db import reset_queries
from django.forms.models import ModelForm
from django.http import request
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from pandas.core.indexes import category
import itertools

from Labels_Nudges.app import get_top_recommendations
from .forms import Personal_infoForm, FoodCategory, FoodCategoryForm,ChoiceEvaluationForm
# from django.forms import formset_factory, modelformset_factory
from .models import  Personal_info, Recipes , SelectedRecipe,EvaluateChoices, Recommendations, SelectedContent
from .app import *
# Create your views here.
# person_id = 0
import string
import random
import re
#def home(request):
#   request.session['person_id'] = 0
#  return render(request, 'Labels_Nudges/homes.html', context={})

def home(request):
    request.session['person_id'] = 0
    #prolific_id = , msg)
    #prolific_id = str(prolific_id.group(1))
    full_url = request.get_full_path()
    #request.GET['PROLIFIC_PID']
    print('Full',request.get_full_path())
    #print(full_url)
    if 'PROLIFIC_PID' in full_url:
        prolific_id = re.search("PROLIFIC_PID=(.*?)&STUDY_ID",full_url)
        request.session['prolific_id'] = str(prolific_id.group(1))
        #print("----------",prolific_id.group(1))
    else:
        request.session['prolific_id'] = '000'
    return render(request, 'Labels_Nudges/homes.html')


def personal_info(request):
    user_selected = Personal_info.objects.filter(id = request.session['person_id'])
    if user_selected:
        Personal_info.objects.filter(id=request.session['person_id']).delete()
    if request.method == 'POST':
        personl_info = Personal_infoForm(request.POST)
        if personl_info.is_valid():
            answer = personl_info.save(commit=False)
            
            rd_str =''.join(random.choice(string.ascii_lowercase) for _ in range(5))
            time_now = datetime.now().strftime('%H%M%S')
            gene_session = 'dars'+time_now +'_'+str(answer.id)+rd_str
            personl_info.instance.session_id = gene_session

            answer = personl_info.save(commit=True)
            
            request.session['person_id'] = answer.id
            gene_session = 'dars'+time_now +'_'+str(answer.id)+rd_str
            personl_info.instance.session_id = request.session['prolific_id']
            
            request.session['session_id'] = gene_session
            answer = personl_info.save(commit=True)

            request.session['person_id'] = answer.id
            return redirect('Labels_Nudges:selectRecipe')
    else:
        personl_info = Personal_infoForm()
    return render(request, 'Labels_Nudges/personal_info.html', context={'form': personl_info})

def ghs_fk(request):
    user_selected = Ghs_fk.objects.filter(id = request.session['person_id'])
    if user_selected:
        ghs_fk.objects.filter(id=request.session['person_id']).delete()
    if request.method == 'POST':
        ghs_fk_form = Ghs_fkForm(request.POST)
        #print('------- Here')
        if ghs_fk_form.is_valid():
            answer = ghs_fk_form.save(commit=False)

            rd_str = ''.join(random.choice(string.ascii_lowercase) for _ in range(5))
            time_now = datetime.now().strftime('%H%M%S')
            gene_session = 'dars' +  time_now + '_' + str(answer.id) + rd_str
            ghs_fk_form.instance.session_id = gene_session
            ghs_fk_form.instance.person_id = request.session['person_id']
            #print(';;;;;;;;;;;here')
            answer = ghs_fk_form.save(commit = True)

            #request.session['person_id'] = answer.id
            return redirect('Labels_Nudges:selectRecipe')
    else:
        ghs_fk_form = Ghs_fkForm()
    return render(request, 'Labels_Nudges/healthy_knowledge.html', context={'form':ghs_fk_form})

def random_recipes():

    h_recipes = sample(list(Recipes.objects.filter(Fsa_new__lte = 8).values_list('id', flat=True)), 5)
    uh_recipes = sample(list(Recipes.objects.filter(Fsa_new__gte = 9).values_list('id',flat=True)),5)
    
    return h_recipes, uh_recipes




def selectRecipe(request):
    user_selected = SelectedContent.objects.filter(id = request.session['person_id'])
    if user_selected:
        SelectedContent.objects.filter(id=request.session['person_id']).delete()
    if request.method == "POST":
        selectedContentM = SelectedContent()
        recipe_id = request.POST.getlist('recipe_id')
        
        # print("------****------",recipe_id)
        
        
        # selectedContent.session_id = gene_session,
        selectedContentM.person_id = request.session['person_id']
        selectedContentM.contentIDs = recipe_id
        selectedContentM.save()
        
        request.session['selectedRecipes'] = recipe_id
        
        return redirect('Labels_Nudges:recipe_recommendations')
    else:
        
        #     categoryForm = FoodCategoryForm()
        recipes, un_recipes = random_recipes()
        # print(recipes, un_recipes)
            # extract 5 healthy recipes
        h_0_recipe =  Recipes.objects.get(id=recipes[0])
        h_1_recipe = Recipes.objects.get(id=recipes[1])
        h_2_recipe = Recipes.objects.get(id=recipes[2])
        h_3_recipe = Recipes.objects.get(id=recipes[3])
        h_4_recipe = Recipes.objects.get(id=recipes[4])
        # extract 5 unhhealthy recipes
        unh_0_recipe = Recipes.objects.get(id=un_recipes[0])
        unh_1_recipe = Recipes.objects.get(id=un_recipes[1])
        unh_2_recipe = Recipes.objects.get(id=un_recipes[2])
        unh_3_recipe = Recipes.objects.get(id=un_recipes[3])
        unh_4_recipe = Recipes.objects.get(id=un_recipes[4])
        # print('-----------', h_0_recipe.salt_count)
        # print('-------',h_0_recipe.content)
        
        h_0 = [h_0_recipe.Name, recipes[0], 'healthy', h_0_recipe.image_link, int(float(h_0_recipe.calories_kCal)),
                                    int(float(h_0_recipe.Servings)),int(float(h_0_recipe.size_g) // float(h_0_recipe.Servings)), h_0_recipe.salt_g,h_0_recipe.sugar_g,h_0_recipe.fat_g,h_0_recipe.saturate_g, h_0_recipe.content]
        # print('%%%%%%%%%%%%%%', h_0)
        h_0_ing = h_0_recipe.content.capitalize()
        
        
        h_1 = [h_1_recipe.Name, recipes[1], 'healthy', h_1_recipe.image_link, int(float(h_1_recipe.calories_kCal)),
                                    int(float(h_1_recipe.Servings)),int(float(h_1_recipe.size_g) // float(h_1_recipe.Servings)), h_1_recipe.salt_g,h_1_recipe.sugar_g,h_1_recipe.fat_g,h_1_recipe.saturate_g, h_0_recipe, h_1_recipe.content.capitalize()]
        h_1_ing = h_1_recipe.content.capitalize()
        
        h_2 = [h_2_recipe.Name, recipes[2], 'healthy', h_2_recipe.image_link, int(float(h_2_recipe.calories_kCal)), 
                                int(float(h_2_recipe.Servings)),int(float(h_2_recipe.size_g) // float(h_2_recipe.Servings)), h_2_recipe.salt_g,h_2_recipe.sugar_g,h_2_recipe.fat_g,h_2_recipe.saturate_g, h_2_recipe.content.capitalize()]
        h_2_ing = h_2_recipe.content.capitalize()
        
        h_3 = [h_3_recipe.Name, recipes[3], 'healthy', h_3_recipe.image_link, int(float(h_3_recipe.calories_kCal)),
                                    int(float(h_3_recipe.Servings)),int(float(h_3_recipe.size_g) // float(h_3_recipe.Servings)), h_3_recipe.salt_g,h_3_recipe.sugar_g,h_3_recipe.fat_g,h_3_recipe.saturate_g, h_3_recipe.content.capitalize()]
        h_3_ing = h_3_recipe.content.capitalize()
        
        h_4 = [h_4_recipe.Name, recipes[4], 'healthy', h_4_recipe.image_link, int(float(h_4_recipe.calories_kCal)), 
                                int(float(h_4_recipe.Servings)),int(float(h_4_recipe.size_g) // float(h_4_recipe.Servings)), h_4_recipe.salt_g,h_4_recipe.sugar_g,h_4_recipe.fat_g,h_4_recipe.saturate_g, h_4_recipe.content.capitalize()]
        
        h_4_ing = h_4_recipe.content.capitalize()
        
        
        unh_0 = [unh_0_recipe.Name, un_recipes[0], 'unhealthy', unh_0_recipe.image_link, int(float(unh_0_recipe.calories_kCal)), int(float(unh_0_recipe.Servings)),int(float(unh_0_recipe.size_g) // float(unh_0_recipe.Servings)),unh_0_recipe.salt_g,unh_0_recipe.sugar_g,unh_0_recipe.fat_g,unh_0_recipe.saturate_g, unh_0_recipe.content.capitalize()]
        
        unh_0_ing = unh_0_recipe.content.capitalize()
        
        
        unh_1 = [unh_1_recipe.Name, un_recipes[1], 'unhealthy', unh_1_recipe.image_link, int(float(unh_1_recipe.calories_kCal)),int(float(unh_1_recipe.Servings)),int(float(unh_1_recipe.size_g) // float(unh_1_recipe.Servings)),unh_1_recipe.salt_g,unh_1_recipe.sugar_g,unh_1_recipe.fat_g,unh_1_recipe.saturate_g,unh_1_recipe.content.capitalize() ]
        
        unh_1_ing = unh_1_recipe.content.capitalize()
        
        
        unh_2 = [unh_2_recipe.Name, un_recipes[2], 'unhealthy', unh_2_recipe.image_link, int(float(unh_2_recipe.calories_kCal)), int(float(unh_2_recipe.Servings)),int(float(unh_3_recipe.size_g) // float(unh_3_recipe.Servings)),unh_2_recipe.salt_g,unh_2_recipe.sugar_g,unh_2_recipe.fat_g,unh_2_recipe.saturate_g, unh_2_recipe.content.capitalize()]
        
        unh_2_ing = unh_2_recipe.content.capitalize()
        
        unh_3 = [unh_3_recipe.Name, un_recipes[3], 'unhealthy', unh_3_recipe.image_link, int(float(unh_3_recipe.calories_kCal)), int(float(unh_3_recipe.Servings)),int(float(unh_3_recipe.size_g) // float(unh_3_recipe.Servings)),unh_3_recipe.salt_g,unh_3_recipe.sugar_g,unh_3_recipe.fat_g,unh_3_recipe.saturate_g, unh_3_recipe.content.capitalize()]
        
        unh_3_ing = unh_3_recipe.content.capitalize()
        

templates/Labels_Nudges/boost.html
{%load static %}
{% load mathfilters %}


<!DOCTYPE html>
<html lang="en">

<head>
    <title>Food Search</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@100&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/radio_h_unh.css'%}">
    <!-- Star field -->
    <!-- <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script> -->

    <link rel="shortcut icon" href="{% static 'icon/icon.png'%}">
    </script>



    <style>
        body {
            background-image: linear-gradient(-225deg, #B7F8DB 0%, #a1d8e9 100%);
            /* background: url("{% static 'back/person_info.jpg' %}") no-repeat center center fixed; */
            /* -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover; */
            /* background-image: linear-gradient(to top, #accbee 0%, #e7f0fd 100%); */
            font-family: 'Nunito', sans-serif;
            padding-top: 70px;
            justify-content: center;
            align-items: center;
            text-align: center;
            margin: 0 auto;
            padding-bottom: 30px;
            min-height: 100vh;
        }

        .container {
            display: flex;
            flex-direction: row;
            max-width: 100%;
            max-height: 100%;
            margin: auto;
            /* justify-content: center; */

        }

        .flex-column {
            display: flex;
            flex-direction: column;
            flex-wrap: nowrap;
            justify-content: flex-start;
            width: 97%;
            max-height: 20%;
            margin: auto;
            border-radius: 12px 12px 12px 12px;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            background: #fbfbfb;
            box-shadow: 1px 2px 8px rgba(0, 0, 0, 0.65);
        }

        .flex-left {
            width: 50%;
            /* height: 100vh; */
        }

        .flex-right {
            width: 50%;
            /* height: 100vh; */
        }


        .btn-lg {
            border-color: #2c7460 !important;
            background: #fbfbfb;
            color: #1f4037;
            /* padding:15px ; */
            margin: auto;
            /* #font-size: 20px; */
            border: 0.10em solid;
            cursor: pointer;
            text-decoration: none;
            font-weight: bold;
            border-radius: 8px 8px 8px 8px;

        }

        .btn-lg:hover {
            background-image: none !important;
            background-color: #8bbdaf !important;
            /* background-image: linear-gradient(-225deg, #c8e9da 0%, #bbd8e0 100%); */
            color: rgb(233, 225, 225);

        }

        /* =---------------- */
        /* 
        * {
            box-sizing: border-box;
        } */




        /* .courses-container {
            border-radius: 12px 12px 12px 12px;
            max-width: 60%;

        } */

        .course {
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 10px 10px rgba(0, 0, 0, 0.2);
            display: flex;
            width: 97%;
            height: 17%;
            /* max-width: 100%; */
            /* max-height: 100%; */
            margin: 20px;
            overflow: hidden;
            /* width: 700px; */
        }

        .course-info h5 {
            color: black;
            font-weight: bold;
        }

        .items h6 {
            color: black;
            font-weight: bold;
        }



        .course-info {
            padding: 0px;
            /* position: relative; */
            display: flex;
            flex-direction: column;
            width: 100%;
        }

        .recipe_items {
            display: flex;
            flex-direction: row;
        }

        .items {
            padding: 10px;
        }


        .btn {
            background-color: #ffff;
            border: 1px solid black;
            border-radius: 50px;
            box-shadow: 0 10px 10px rgba(0, 0, 0, 0.2);
            color: black;
            font-size: 16px;
            padding: 12px 25px;
            letter-spacing: 1px;
            margin: auto;
            /* margin-bottom: 10px; */
            /* position: fixed; */
        }



        .course-preview img {
            width: 100%;
            height: 100%;
            max-width: 100%;
            display: block;

        }

        .course-preview {
            width: 300px;
            /* border: 5px solid black; */
        }

        ul {
            list-style: none;
        }

        .django-starfield:not(:checked)>input {
            position: absolute;
            /* top: -9999px; */

        }



        .django-starfield:not(:checked)>label {
            width: 1.5em;
            height: 2em;
            overflow: hidden;
            /* white-space: nowrap;
            cursor: pointer;
            font-size: 20px; */
            color: #00f5fd;
            font-weight: bolder;


        }


        .django-starfield>input:checked~label {
            color: #3251d8;
        }

        /* ------------------*/
    </style>
    <script>
        document.getElementById("id_f_1-recipe_0").checked = true;
    </script>
</head>

<body>
    <div class="flex-column" style="height:100%;">
        <div>
            <div>
                <h3 style="font-size: 40px;
                font-weight: 400;
                line-height: 30px;
                font-style: bold; margin-top: 30px;">Understanding the use of nutrition labels</h3>
                <h4 style="font-size: 20px;
                font-weight: 350;
                line-height: 30px;
                font-style: bold; margin-top: 10px;">Presented below is the full description of how Multiple Traffic nutritional labels work. Please read
                carefully and processed to get personalized recipes.</h4>
            </div>



            <hr style="  border: 0; 
                height: 1px; 
                background-image: linear-gradient(to right, #f0f0f0, #00b9ff, #59d941, #f0f0f0);" />
        </div>

        <form action="" method="POST">

            {% csrf_token %}
            <div class="container">
                <!-- ================= left bar ================= -->

                <img src="{% static 'icon/boost.jpg'%}" alt="" style=" max-width: 100%;
                margin: auto;
                display: block;">

            </div>
            <hr style="  border: 0; 
                height: 1px; 
                background-image: linear-gradient(to right, #f0f0f0, #00b9ff, #59d941, #f0f0f0);" />
            <div style="text-align: right; margin-bottom:40px; margin-top:30px; margin-right: 20px;">
                <button type="submit " name="submit" class=" btn-lg col-3"> Next </buttton>
            </div>
        </form>
    </div>
    <!------------------------- Next --------------------------->

    </div>

</body>

templates/Labels_Nudges/csv_form.html
{% extends 'admin/base.html' %}


{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}

templates/Labels_Nudges/homes.html
{% extends 'Labels_Nudges/main.html'%}
{%load static%}
{% block content %}


<div class="header-bar">
    <!-- <div class="row"> -->
    <div class="col-lg-2">
        <img src="{% static 'icon/icon.png'%}" alt="" style=" 
            width: 160px;">
    </div>
    <div>
        <h1>Personalized Recipe Recommendation </h1>
    </div>
    <!-- </div> -->
</div>


<div class="container">

    <h2 style="margin: auto; padding: 20px; text-align: center;">Welcome </h2>



    <p>Welcome to our study! The aim of this study is to understand how we can use technology to suggest new recipes to
        people, based on their preferences.
        This study is part of the PhD research of Ayoub El Majjodi
        at the University of Bergen, Norway, under supervision of Prof. Dr. Christoph Trattner and Dr. Alain Starke.
        <br>
        Please carefully read the procedure followed in this study to give your informed consent for voluntary
        participation*.
    </p>
    <b>Procedure</b>
    <br>
    <!-- <p>
You will be first asked to answer a few questions about your personal characteristics. Then, you are asked to choose a preferred food category, and to disclose your preferences for recipes in terms of their popularity, serving size, 
cooking time and the number of ingredients.        
<br> -->
Based on your personal preferences, you will afterwards be presented a list of ten personalized recipe recommendations. From that list, please select one recipe that you like the most and would like to cook at home. Afterwards, you will be asked a few questions about the chosen recipe and the decision-making process.

    </p>
    <b>Duration and compensation</b>
    <p>The study takes around 5-7 minutes to complete. By clicking the <b>'Start'</b>
        button, you agree to have read and understood this consent form.</p>
    <!-- <p><b>Note:</b> <b style="color: red;">Due to the complex computations involved, page loading time may take up to 1 min. 
        Please bear with us and thank you for your patience.</b></p> -->

    <div style="text-align: center;">
        <a type="button" value="Start" class="btn-lg" href="{% url 'Labels_Nudges:personal_info' %}"> Start </a>
    </div>
    <hr style="  border: 0; 
height: 1px; 
background-image: linear-gradient(to right, #f0f0f0, #00b9ff, #59d941, #f0f0f0);" />
    <p style="font-size: 14px; padding-top: 10px; padding-bottom: 10px; color: black;"> <i
            style="color: red;">*</i> 
            The collected information is used for writing scientific
             publications and is only reported at the group level. Your personal information 
             is processed anonymously and it cannot be traced back to you. 
             For questions about the study, please contact the experimenter, Ayoub El Majjodi: Ayoub.Majjdo@uib.no
    </p>

</div>

{% endblock%}

templates/Labels_Nudges/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Food Search</title>
    
    <!-- <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
     -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@100&display=swap" rel="stylesheet">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="{% static 'icon/icon.png'%}">

    <style>
        body {
            background: url("{% static 'back/rcp_7.jpeg' %}") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            font-family: 'Nunito', sans-serif;
            padding-top: 70px;
        }

        .header-bar {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
            color: #fff;
            padding: 20px;
            box-shadow: 1px 2px 8px rgba(0, 0, 0, 0.65);
            border-radius: 8px 8px 0 0;
            /* background: linear-gradient(90deg, #EEA390 0%, #EB796F 43%, #EB796F 100%); */
            /* background: linear-gradient(90deg, rgba(110,181,103,0.9995185574229691) 24%, rgba(39,210,133,1) 44%, rgba(142,217,183,1) 87%); */
            background: #1f4037;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #99f2c8, #1f4037);
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #99f2c8, #1f4037);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

            max-width: 70%;
            height: 150px;
            margin: auto;


        }

        .container {
            box-shadow: 1px 2px 8px rgba(0, 0, 0, 0.65);
            width: 70%;
            margin: auto;
            border-radius: 0 0 8px 8px;
            background-color: #ffff;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            justify-self: center;
            align-items: center;
        }


        h1,
        h2,
        h3 h4,
        h5,
        h6,{
            font-family: 'Releway', sans-serif;
        }

        .btn-lg {
            border-color: #2c7460 !important;
            background-color: #FFF;
            color: #1f4037;
            padding: 0.3em 4.2em;
            font-size: 20px;
            border: 0.10em solid;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
            font-weight: bold;

        }

        .btn-lg:hover {
            background-image: none !important;
            background-color: #1f4037 !important;
            color: seashell;

        }
    </style>

</head>

<body>
    {% block content %}

    {% endblock %}
</body>

</html>

templates/Labels_Nudges/recipe_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="import-csv/">Import CSV</a>
    <br />
    {{ block.super }}
{% endblock %}

templates/Labels_Nudges/thanks.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Food Search</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css">
    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <style>
        @import url(//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css);
        @import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
    </style>
    <link rel="stylesheet" href="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/default_thank_you.css">
    <script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/jquery-1.9.1.min.js"></script>
    <script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/html5shiv.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="{% static 'icon/icon.png'%}">

    <script>
        function myFunction() {
            /* Get the text field */
            var copyText = document.getElementById("myInput");

            /* Select the text field */
            copyText.select();

            /* Copy the text inside the text field */
            document.execCommand("copy");

            /* Alert the copied text */
            alert("Copied the text: " + copyText.value);
        }
    </script>

</head>

<body>
    <header class="site-header" id="header">
        <h1 class="site-header__title" data-lead-id="site-header-title">THANK YOU</h1>
    </header>

    <div class="main-content">

        <p class="main-content__body" data-lead-id="main-content-body">Thanks a bunch for filling that out. We really
            appreciate you giving us a moment of your time.</p>


        <div>
            <p for="">Please copy & paste the code below to Prolific in order to obtain your payment for your participation.</p>

            <input class='col-6 form-control-lg' type="text" value="6B77F988"  id='myInput' readonly>
            <button type="submit" class="btn-lg btn-success form-control-lg" onclick="myFunction()">Copy !</button>
        </div>
    </div>
    <footer>
        <p class="copyright" style="position:relative;
        color: #e4dcdc;
        bottom: 0;

        "> &#169; <a href="https://dars.uib.no/"> DARS RESEARCH GROUP</a></p>
    </footer>
    <i class="fa fa-thumbs-up main-content__checkmark"></i>
</body>

</html>